name: Main

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GIT_AUTHOR_NAME: github-actions[bot]
  GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
  GIT_COMMITTER_NAME: github-actions[bot]
  GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com

jobs:
  daily-summary:
    runs-on: ubuntu-22.04
    env: 
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Daily summary
        run: ./summary.sh daily
        env:
          BRANCH: master,branch-3.0,branch-2.11,branch-2.10

      - name: Push
        run: |
          git commit -a -m "chore: daily summary" -s
          git push
